import type { Metadata } from "next";
import { DM_Serif_Display } from "next/font/google";
import Preloader from "@/components/Preloader";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

const dmSerifDisplay = DM_Serif_Display({
  weight: "400",
  subsets: ["latin"],
  style: ["italic", "normal"],
  variable: "--font-dm-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${dmSerifDisplay.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Preloader>
          <Navbar />
          {children}
        </Preloader>
      </body>
    </html>
  );
}
